ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER ELECTRON_USER IDENTIFIED BY password_do_zmiany;

GRANT CONNECT, RESOURCE TO ELECTRON_USER;
GRANT CREATE SESSION TO ELECTRON_USER;
GRANT UNLIMITED TABLESPACE TO ELECTRON_USER;
