ALTER SESSION SET CONTAINER = FREEPDB1;

ALTER SESSION SET CURRENT_SCHEMA = ELECTRON_USER;

CREATE TABLE USERS
(
    USER_ID  VARCHAR2(32) DEFAULT SYS_GUID() PRIMARY KEY,
    EMAIL    NVARCHAR2(50) NOT NULL UNIQUE,
    USERNAME NVARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE USER_CREDENTIALS
(
    USER_ID  VARCHAR2(32) PRIMARY KEY,
    PASSWORD VARCHAR2(128) NOT NULL,
    CONSTRAINT FK_USER_CREDENTIALS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);